# Theory: A regime-strength model of electoral manipulation

\chaptermark{Theory}

## Two theories of election manipulation
<!--
- What is electoral manipulation?
  - In this book, focus is on illegal electoral manipulation.
  - Look to Schedler chain of democratic choice to explain
  - See also Simpser 2011 p. 35 on three goals of his definition, and what tactics he includes
    - In particular, he notes the analytic importance of choice (someone is making a deliberate choice to manipulate)
    
-->
    
This book has two principal aims. First, as detailed in Chapter 3, it aims to demonstrate that protest risk is insufficient to restrain election manipulation, a proposition that goes against a substantial body of prior work and has normatively pessimistic implications for democratization. Second, it articulates an alternative theory of electoral manipulation and protest, which explains how manipulation efforts are constructed and how they can be dismantled. This theory is developed in this chapter. To put this discussion on firm footing, it is first necessary to pin down the concept of electoral manipulation.

Over time, scholars have advanced four approaches toward the definition of electoral manipulation. Two of these are rooted in local understandings of election integrity, and two appeal to broader standards [@birch2011]. The first, and simplest, definition of electoral manipulation focuses on whether particular actions are violations of local electoral law. This, of course, poses two difficulties: what is legal in one context may be illegal in another, and---even more problematic---laws themselves may be structured to advantage one party over others. A second approach focuses on local norms, rather than (or in addition to) local legal conditions. Electoral behaviors that may be considered unacceptable in some contexts, may be broadly acceptable in others. This possibiluity has been especially important in studies of vote-buying, where some scholars have emphasized the coerciveness of the practice (e.g. with monitoring and punishment for defection), while others have emphasized cultures of reciprocity and mutual support which can underpin the vote-buying relationship and lead recipients to view such 'gifts' as legitimate [@Lawson2014;@Nichter2018a;@greeneMoneyCantBuy2024]. 

These local approaches to election integrity have, however, largely given way to approaches that make claims at universality. The third school grounds its understanding of electoral manipulation in international law---in particular the Universal Declaration of Human Rights and the UN International Covenant for Civil and Political Rights [@Norris2013]---and the subsequent development of global norms for election management and election monitoring [@kelley2008;@hyde_catch_2011]. Lastly, a fourth approach is grounded in democratic theory; it begins by identifying the elements that are necessary for a democratic election to take place, and defines election manipulation as institutions and behaviors which obstruct those elements. Though this last school of thought is founded upon democratic theory espoused by Dahl [-@dahlPolyarchyParticipationOpposition1971], among others, it has perhaps been most clearly articulated in Andreas Schedler's [-@schedler2002] "menu of manipulation." In it, Schedler identifies seven requirements for a democratic election to succeed, ranging from the delegation of power to elected positions (i.e. elected officials must hold real power, rather than ceremonial or ineffective positions) to the irreversibility of electoral outcomes. Other essential features of a democratic election include freedom to form parties and compete in elections, voting eligibility for all full members of the community, free formation and expression of preferences, and fair aggregation of preferences under the principle of 'one person, one vote.'

Here, I follow this latter school of thought, rooted in democratic theory, for a broad definition of electoral manipulation. To paraphrase Shchedler [-@Schedler2013, p. 83], electoral manipulation in general refers to any and all techniques that limit the choices of political authorities among a community of free and equal citizens. The focus of this book, however, is on a subset of violations of the 'chain of democratic choice;' those tactics which are *procedurally illegitimate* and *carried out by individuals*. I refer to this class of manipulative tactics as *illicit, individual manipulation.* Election manipulation techniques are procedurally illegitimate when they break the established rules for allocating power [@beethamLegitimationPower2013], or more broadly when they depart from the principles of neutrality, fairness, and voice [@vandenbosWhenWeNeed1998;@tylerWhyPeopleObey2006]. <!-- [NOTE: More on this from prior work?] -->

Illicit, individual manipulation excludes most examples of formal electoral manipulation identified by Schedler [-@schedler2002], such as the creation of biased electoral rules or longstanding disenfranchisement of groups of citizens. So long as these tactics are procedurally legitimate---insofar as they are adopted according to the law---they do not expose their perpetrators to personal legal risk. Legislators who approve gerrymandered maps, for instance, may expose themselves to some reputational or political risks if the decision proves unpopular. But they are unlikely to be charged with a crime for doing so. 


On the other hand, a wide variety of procedurally illegitimate forms of electoral manipulation are enacted by individuals around election time. These include---at minimum---vote-buying, voter pressure, ballot-stuffing, multiple voting, and falsification. This framing includes economic electoral intimidation [@fryeWorkplacePoliticsHow2025] and non-state forms of electoral violence, but would likely exclude officially state-sanctioned electoral violence like police disruption of opposition gatherings [@birchElectoralViolenceCorruption2020]. 

The reader may be excused for wondering: why devote a book-length discussion to illicit, individual forms of election manipulation? It is a well-developed position in the literature that incumbents should prefer to rely on exactly the opposite kind of manipulation (i.e. formal techniques), which tend to be less visible and thus less damaging to incumbents' legitimacy, and can also be highly reliable [@birch2011;@Norris2013;@Szakonyi2021]. Nevertheless, there are several reasons for scholars to focus on illicit forms of manipulation. 

First, it is this kind of manipulation---falsification, ballot-stuffing, vote-buying, and the like---which forms the backstop to other, more predictable forms of institutional manipulation. Gerrymandered districts and biased electoral systems can backfire when incumbent popularity is low. Even when the genuine opposition has been excluded from the ballot, and there is thus no risk of incumbent defeat, incumbents still often turn to deliberate, personal forms of electoral manipulation; uncompetitive elections tend to depress turnout, which incumbents must compensate for in order to maintain an image of electoral strength.

Moreover, these techniques are theoretically important as the kind that is most likely to spark protest (due to procedural injustice and revealed information about incumbent), *and* as the most likely to be called out by observers. Because procedurally illegitimate forms of manipulation break the rules, they simultaneously increase protest risk (i.e. incur legitimacy costs) and produce individual risk for the perpetrator. The importance of this latter factor, however, has not previously been developed.

## Leader-oriented theories of manipulation

Until relatively recently, most scholarship on election manipulation focused on the costs and benefits that accrue to the leaders who order it. Most basically, of course, political leaders seek to manipulate elections in order to ensure victory. Simpser [-@simpser2013, p. 61] calls this the 'first conventional wisdom' of research on election manipulation: that its main goal is to ensure that a particular party or candidate wins the election at hand. The competitiveness of the election and stakes of losing power are the main drivers of manipulation in this tradition. Incumbents have more to gain from election rigging when they are likely to narrowly lose the election without it [@nybladeWhoCheatsWho2008;@lehoucq2002;@kamSecretBallotMarket2017;@Birch2007;@Fukumoto2011], and when the prospect of losing carries significant costs [@ziblatt2009;@baturoDemocracyDictatorshipTerm2014;@acemoglu2005economic;@Schedler2013;@horzElectoralManipulationPolarized2021]. Subsequent research has identified broader benefits of rigged elections for leaders; by communicating information about the strength and durability of the regime, manipulation can lead other actors in society to comply with the incumbent [@simpser2013;@gehlbach2015electoral].

Against these benefits, political leaders are expected to weigh the costs of manipulating elections. Election rigging has unavoidable material and organizational costs. More significant to leader-oriented theories, however, is the notion of legitimacy costs [@birch2011]. Scholars often understand legitimacy as individuals' subjective sense that authorities have the right to rule, even if the individual may object to authorities' particular decisions [@Lipset1960]. Legitimacy, in turn, makes it more likely that individuals will comply with authorities' demands [@Levi_Sacks2009]. 

The legitimacy cost of electoral manipulation, then, is both psychological and potentially behavioral. A reduction in individuals’ subjective evaluation that elected authorities have the right to govern can be associated with reduced willingness to obey the government [@Schedler2013]. Birch [-@birch2011] cites protest risk to the cost of manipulation explicitly, saying legitimacy costs "...can be understood in terms of the proportion of the population that can be expected to acquiesce to having their contribution to public choice taken from them or distorted. As a result, she writes, "The capacity for popular mobilization and protest ought to be negatively correlated with electoral malpractice" (p. 58). Schedler [-@Schedler2013] has further usefully defined legitimacy costs as a function of the severity and visiblity of the manipulation employed (p. 274).

This understanding of the cost of electoral manipulation---as a reduction in legitimacy and associated increase in the risk of mass protest---has been widespread in the literature. It has been especially foundational to formal models of electoral manipulation, where loss of support and/or protest risk often stand as the main downside for incumbents [@Little2015;@littleFraudMonitoringNoncompetitive2015;@chernykh2015third]. For instance, Magaloni [-@magaloni2010] writes that, "The legitimacy loss of fraud can be conceived as the costs to the autocrat of damaging its reputation before its own supporters and/or before the international community." 

Protest risk as the cost of manipulation also figures in less formal theory. It is central to the literature on election monitoring [@hyde_2012_marinov;@kelley2012] Manipulated elections can serve as a focal point for citizens' diverse grievances, raising the likelihood of protest [@tucker2007;@higashijimaDictatorsDilemmaBallot2022]. And, by the same token, election fraud figures prominently in general theories of electoral protest.  Higashijima [-@higashijimaDictatorsDilemmaBallot2022] writes that elections can destabIlize authoritarian rule when "a dictator engages in excessive electoral manipulation to such a degree that it... makes it difficult for opposition leaders to correctly estimate the dictator’s true strength and makes it easy to capitalize on popular grievance, provoking popular protest" (p. 10). His analysis shows that excessive electoral fraud makes popular protest initiation more likely [@higashijimaDictatorsDilemmaBallot2022].

However, as discussed in the following chapter, the overall empirical record on the relationship between election manipulation and protest is mixed. Such theories also elide the fact that a large-scale election manipulation operation requires the willing cooperation of large numbers of middlemen, brokers, supervisors, and front-line agents [@saikkonenCoordinatingMachineSubnational2021;@zarazaga2014brokers;@Forrat2018;@larreguy2016parties;@Szwarcberg2015]. Scholars have come to recognize the importance of these networks of agents in limiting or permitting large-scale manipulation [@rundlett2016deliver;@choWhenAgentsDeliver2025;@Harvey2019]. Yet scholars have largely focused on agents' incentives to participate in manipulation efforts, and largely assumed away the idea that participation may carry risks for agents. A more complete picture of agents' behavior will emerge when risks, as well as benefits, are theorized. In turn, this will enable us to develop a more comprehensive theory of electoral manipulation, with significant implications for authoritarianism and democracy. Before describing the theory in detail, I take a brief detour into history to highlight the rise and fall of election manipulation in the world's oldest electoral democracies, the United Kingdom and the United States. Lessons from this sketch will help illuminate the twinned roles of patronage and personal risk in enabling and constraining election manipulation.


## A brief historical sketch: The rise and fall of election manipulation in Britain and United States

Naturally, the earliest entrepreneurs of election manipulation are to be found in the oldest democracies. For instance, 19th century British elections (after the expansion of the franchise to larger classes of people) were characterized by widespread voter pressure, vote-buying, 'treating,' and 'personation.'^['Treating' refers to the practice of plying voters with food and fortifying beverage before and after the vote; 'personation' refers to ineligible voters casting ballots on behalf of someone else.] Just like their modern descendants, those who sought to manipulate early democratic elections were embedded in hierarchical patronage networks. Laborers in the more agricultural counties often faced pressure from large landowners, via the tenant farmers who rented the land. In the boroughs, vote-buying was so common as to appear to many voters a normal part of the electoral process [@hoppenRoadsDemocracyElectioneering1996]; candidates relied on diverse agents to monitor local communities, distribute largess throughout the constituency, and mobilize voters [@campCatalystCauseLegislation2014]. 

Throughout the kingdom, candidates hired 'roughs' to blockade polling places, intimidate and harass opposing voters, interrupt opponents' meetings, and to defend themselves from the opposing side [@blaxillElectoralViolenceEngland2025]. Candidates relied on extensive networks to engage such workers, for two reasons. First, gentlemanly candidates might lack direct connections to the rougher sort of citizen. In the city of Norwich, candidates relied on publicans "who were well-known for their experience in this kind of business," to furnish roughs [@blaxillElectoralViolenceEngland2025]. Second, extended recruitment networks helped protect the candidates from liability for violence. As Blaxill et al [-@blaxillElectoralViolenceEngland2025] write, "roughs were hired by sub-agents, committee members or general prominent party supporters, thus providing a firebreak to the chief agent or candidate if the roughs themselves talked, freely or under detention" [@blaxillElectoralViolenceEngland2025, p. 191].

Such activities persisted unabated after the the passage of the Corrupt Practices Act of 1854 [@hoppenRoadsDemocracyElectioneering1996], which defined various electoral offenses but was largely toothless. Under the act, vote buyers---well-resourced politicians---faced the prospect of forfeiting 100 pounds, while vote sellers could forfeit ten. To initiate these proceedings against a lawbreaker anywhere in England, however, private citizens would have to sue in court in London [@ActConsolidateAmend]; this could entail a journey of several days. Only with the passage of the Illegal Practices Prevention Act of 1883 did these practices begin to diminish [@hoppenRoadsDemocracyElectioneering1996]. The 1883 Act put prosecution in the hands of the state, rather than individual citizens, allowed trials to be held in any relevant court, and increased the penalties for various electoral crimes [@IllegalPracticesPrevention]. Under the new law, those found guilty of bribery, treating, abduction of voters, undue influence, personation, or filing false campaign expenditure statements could face up to one year in prison (possibly to include hard labor), a 200-pound fine, the loss of voting rights, and the loss of the right to stand for election [@olearyEliminationCorruptPractices1962].

The Act also sought to break up politicians' patronage networks by limiting the number of electoral agents they could field and the maximum campaign expenses they could lawfully spend [@olearyEliminationCorruptPractices1962]. This, in combination with the fact that candidates could be held criminally liable for the misbehavior of their agents, helped lead to the decline of 'roughs' in British politics; increasingly large and professional police forces also helped [@blaxillElectoralViolenceEngland2025].  Parties and candidates went to great lengths to warn their agents to obey the law. "This Act is not to be trifled with," wrote one Conservative journal in 1896. "Its penalties amount to social ruin, and will, without doubt, be strictly enforced" [@rixEliminationCorruptPractices2008]. The effect of the law "was to transform the whole character of British electioneering within a generation" [@olearyEliminationCorruptPractices1962].

American elections in the 1800s also frequently featured 'treating,' ineligible or multiple voting, voter intimidation, ballot-stuffing, 'colonizing',^[Importing voters from a neighboring district.] 'cooping',^[The act of kidnapping and drugging individuals, and compelling them to vote (often more than once). See Bensel [-@benselAmericanBallotBox2004] for examples.] and outright fraud [@reynoldsSymbioticRelationshipVote1993;@benselAmericanBallotBox2004;@argersinger1985new;@cox1981turnout;@argersingerGreatConspiraciesStealing2024;@foleyBallotBattlesHistory2024;@summersPartyGamesGetting2004]---to say nothing of the systematic restrictions and repression aimed at Black citizens [@epperlyRuleViolenceRule2020]. These types of manipulation reached their apex in the United States' urban political machines, which sustained themselves through a mutually reinforcing cycle: election manipulation enabled the capture of political office, which allowed politicians to direct patronage resources (i.e. jobs, contracts), which in turn fueled further manipulation. 

Patronage---the funneling of jobs, contracts, and opportunities for graft to supporters---was essential to the operation of New York City's Tammany Hall machine, which dominated city politics for much of the late nineteenth and early twentieth centuries. At its peak, the machine had the ability to distribute patronage on a massive scale, having allies in the governor, the mayor, the city comptroller, and more. Its most famous leader, William "Boss" Tweed, kept plum sources of jobs for himself as Commissioner of Public Works and executive roles in a variety of industries [@callowTweedRing1972]. "Control of patronage enabled Tweed to become New York's first absolute boss," Callow [-@callowTweedRing1972, p. 117] writes in his deep history of the Tammany machine. "From the ward leader down to the precinct captain, power depended on the ability to supply patronage to the faithful. ...through patronage alone [the machine] employed at least 12,000 people [and] 33 per cent of the money supplied to the city departments was stolen, in the sense that it went to men listed on the payrolls who did no work, or to payroll names which were fictitious." These men, in turn, were expected to deliver votes for the Tammany machine at election time.

American political machines were early pioneers in the use of what observers of post-Soviet politics would call "administrative resources" to control clients and influence elections [@Allina-Pisano2010]. Large corporations were extorted with the threat of tougher regulatory legislation. But small businesses---the merchant, innkeeper, stable owner, etc.---were extorted through the selective 'enforcement' of city ordinances. "...the bible of graft was the bulky volume of over 900 pages of city ordinances. The Ring used it to harass, blackmail, and demand illegitimate fees" [@callowTweedRing1972, p. 190]. Small businessmen who failed to pay the machine's fees or to turn out votes on election day faced the prospect of fines, closure, water shut-off, and other obstacles [@callowTweedRing1972, pp. 190-197].^[In this approach, the Tweed machine anticipated the tactics of bureaucratic extortion in the post-Soviet space [@vasilevaTrappedInformalityBig2018;@madlovicsPostcommunistPredationModeling2021].] 

Yet the success of Tammany Hall depended just as much on managing legal risks to its network of agents as it did on patronage resources. Indeed, control of patronage and control of the legal system each depended on the other, with election manipulation as the link. The Tammany machine owed its dominant position to the ability of its clients to deliver votes on election day. While many of these votes were honest---or at least not directly purchased or coerced---manipulation was an essential ingredient. Gangs of toughs were dispatched to drive away reformist voters, intimidate election judges, attack opposition toughs^[Reflecting later on this bygone era of politics, one politician lamented: "Nobody gets killed any
more and the ambulances and patrol wagons stay in their garages.... It was wonderful to see my men slug the opposition to preserve the sanctity of the ballot... [@callowTweedRing1972, p. 209].], and to exercise their own franchise as often as they could. Pliant judges naturalized immigrants en masse, creating new voters sometimes at the pace of thousands a day. Voter registration lists were padded with the names of deceased and fictitious individuals. Tammany allies serving as election judges adjusted the results as needed. Votes were bought in cash, food, or liquor [@callowTweedRing1972, pp. 207 - 213]. 

All of these activities required that Tammany Hall be able to protect its agents from legal consequences. One of the machine's first orders of business was to secure the loyalty of the police, to install friendly judges in office, and to ensure that machine allies served as District Attorney. Friendly police officers, lawyers, and judges could help the alleged offender at any stage of the judicial process. One Tammany-affiliated prosecutor (who would later become mayor) was said to have prosecuted over 12,000 cases, but to have quashed 10,000 more [@callowTweedRing1972, p. 39]. The *Times* complained of this practice, writing that rather than bring indictments, the District Attorney "waits year after year for the benign influences of our Christian civilization to soften [suspects'] hearts. They naturally feel grateful for this forbearance...and testify their gratitude by working for him at elections" [@callowTweedRing1972, p. 148]. Well-connected lawyers worked hard on election day, getting those repeaters who were caught out of custody and back to work [@callowTweedRing1972, p. 150]. 

Despite these formidable resources, it could still be wise for front-line agents to take precautions to avoid detection. Disguises and costume changes were common. One Tammany Hall tough would rotate his gang of bearded repeaters through barbershops in between casting ballots [@callowTweedRing1972, p. 210]:

> When you've voted 'em with their whiskers on, you take 'em to a barber and scrape off the chin fringe. Then you vote 'em again with the side lilacs and a mustache. Then to a barber again, off comes the sides and you vote 'em a third time with the mustache. If that ain't enough and the box can stand a few more
ballots, clean off the mustache and vote 'em plain face.


As Callow writes [-@callowTweedRing1972, pp. 150-151]:

> The Tweed Ring, then, in consolidating its power, seized the legal machinery of New York to make it the backbone of its organization. Without it other operations like election fraud were in danger of exposure and prosecution. Thus the Ring helped to establish one of the classic patterns of a corrupt political machine. Its alliance with venal judges, the underworld, the police, and shyster lawyers kept the machine moving, providing not only patronage, jobs, and graft, but also the means to protect and control organized
crime. Fundamentally, however, it provided security and safety the legal obstructions to obscure public plunder. 

Though the political machines had formidable resources to deploy at election time, there were nevertheless large constituencies dissatisfied with their rule---these might include supporters of the local opposition party, those who resented the inefficiency and corruption of machine government, and professionals and corporations who desired a more regular legal environment [@summersPartyGamesGetting2004, p. 230]. At times of significant discontent, these constituencies could bring reformers to power. These reformers sought to break the power of the machine along both fronts that sustained it: by limiting politicians' freedom to distribute jobs (and the attendant opportunities for graft) to their clients, and by increasing the costliness of rigging elections. 
Civil service reform was the primary tool for constraining patronage and its influence on elections. Writing in 1919, a prominent reformer and Indiana politician argued that, just as the introduction of the Australian ballot removed the temptation to buy or coerce votes (by concealing whether the voter had in fact complied), the Pendleton Act of 1883 removed the incentive to "that kind of corruption which is nourished by the hope of office" [@foulkeFightingSpoilsmenReminiscences1919, p. 10]. 

The Pendleton Act granted protections from dismissal to certain classes of federal employees, established the Civil Service Commission, and mandated merit-based examinations for appointments to civil service jobs. In so doing it, limited the ability of incoming administrations to remove incumbents and open up jobs to their clients; it also limited their ability to reward influential clients with lucrative federal employment. While this directly cut down on federal patronage opportunities, it also indirectly cut into political machine's campaign war chests."At the heart of party finance," Summers writes, "was the principle of assessment on officeholders.... In return for being rewarded an office, the loyal partisan was expected to pay some of his or her salary to campaign funds" [-@summersPartyGamesGetting2004, p. 150]. The more lucrative the office, the larger the expected donation by the officeholder; those who failed to repay their patron's generosity could be dismissed in favor of someone more loyal.

The federal patronage system was the center of gravity for affiliated local machines; senators, representatives, and local bosses all had claims on the president's appointments within their domains [@foulkeFightingSpoilsmenReminiscences1919].  Federal civil service reform removed some of the choicest patronage prizes from the game, reducing the incentive to rig elections. Reformers pushed for similar changes at the municipal level, which naturally faced stiff resistance from the machines [@summersPartyGamesGetting2004].  



<!--The United States' political machines were undone by a combination of forces [@digaetanoWhyDidPolitical1985], including the rise of the programmatic welfare state, divisions within their own ranks, changing patterns of immigration and ethnicity, and successful efforts to limit the scope of political patronage. -->


Control over police departments and prosecutor's offices was an especially important battleground. Patronage-based police forces not only protected the machine's agents on election day, but also paid into the machine's coffers a share of the bribes and payoffs the department collected [@summersPartyGamesGetting2004, p. 155]. In one example of contestation over the police, the rivals of the Tammany machine, state-level Republicans, capitalized on public discontent to launch a state Senate investigation of the New York City police in 1893. The Lexow Committee report, containing over 1,000 pages of testimony of police interference with elections, concluded that "almost every conceivable crime against the elective franchise was either committed or permitted by the police," in the interests of Tammany Hall [@bermanTamingTigerLexow1980]. The committee's recommendations for police reform include a bipartisan supervisory board, and the creation of a civil service merit system for hiring and promotion of officers; these changes were incorporated into the reformed Greater New York charter of 1898 [@newyorkcityCharterGreaterNew1897], weakening partisan control over the police. While reformers and traditionalists would trade power over the years in New York and elsewhere [@bermanTamingTigerLexow1980;@walkerPopularJusticeHistory1980], these changes helped foster norms of professionalism and impartiality that would become enshrined in US Supreme Court doctrine, the manuals of the Department of Justice, and the guidelines of the American Bar Association [@greenWHENPROSECUTORSPOLITICK2020]. The norm of professional prosecution, "without fear or favor," helped uproot a long American tradition of election manipulation during the 20th century.

The mutually reinforcing loss of patronage resources and diminution of legal impunity intensified principal-agent problems within the machines. Even when machines were working properly, principal-agent problems abounded. Agents tasked with delivering votes could steal from the machine at a prodigious pace. One Pittsburgh boss dispatched two agents with $40,000 for 'election-day expenses' to an allied machine in Indianapolis; the men arrived, but the cash never did [@summersPartyGamesGetting2004, p. 11]. Disputes over finite patronage opportunities could fracture the machines. "The Ring and the Boss," wrote one observer of the machine era, "command an army composed of elements as dangerous as those which make up the crew of a pirate ship. The instant the slightest sign of weakness is shown, each man aspires to be commander, and is willing to sink the ship and all on board rather than to forego his own ambitious schemes" [@shapleySolidMulhoolyPolitical1889]. Indeed, the beginning of the end of Tweed era of Tammany Hall came when a highly-placed client, disgruntled over unpaid claims by the machine, leaked a trove of incriminating accounts to the *New York Times* [@callowTweedRing1972, pp. 259-260]. The Pendleton Act itself was passed, in part, due to the assassination of President Garfield by a disappointed office-seeker. 

To summarize, election manipulation in the early days of mass suffrage in the United Kingdom and United States bears a strong resemblance to the techniques we see in modern electoral authoritarian and electoral democratic regimes. Economic intimidation, vote-buying, violence, and falsification abounded, producing locally dominant political party machines. These efforts were organized along the lines of patronage networks, stretching from politicians and wealthy elites at the top down to the ordinary voter at the bottom. Rigged elections flourished when control over patronage also enabled legal impunity for election-manipulating agents. Reformers targeted both aspects of the machine in order to hold cleaner elections and capture power: the restrictions of patronage resources and the reduction of political control over police, prosecutors, and courts. 

## An agent-risk model of electoral manipulation
<!--
- What does extensive manipulation require? Solving a principal-agent problem
- P-A nature of election manipulation
- How to solve?
  - Patronage resources (much discussion will be needed)
    - Mobilizational resources 
    - Incentives for supporting the boss
  - Legal impunity for agents
-->
  
The foregoing historical sketchm, and much modern research, confirm that incumbents who wish to manipulate elections extensively need a large network of subordinates willing to expend resources and undertake personal risks. The earliest generation of modern research on electoral manipulation often assumed, for the sake of parsimony, that whatever level of manipulation the incumbent ordered was smoothly carried out. A subsequent generation of research on authoritarian politics has emphasized the risks incumbents face from their subordinates [@svolik_politics_2012;@svolikPowerSharingLeadership2009;@magaloni2008credible], the abundance of principal-agent problems in such environments [@rundlett2016deliver;@Harvey2019;@tysonAgencyProblemUnderlying2018], and the difficulty of monitoring low-level agents [@Larreguy2016;@Boix2013]. It is, consequently, no small feat to mobilize thousands or tens of thousands of individuals to stuff ballot boxes, bribe voters, or falsify election returns. Doing so requires that the incumbent have considerable influence over high-level actors like political party leaders, regional governors, big business owners, and so on. These high-level actors, in turn, must be able to exercise influence over meso-level actors like regional legislators, mayors, town councilors, and firm managers, etc. Finally, these meso-level actors must be able to exercise influence over the front-line agents---precinct election officials, low-level civil servants, party operatives, etc.---and even individual voters themselves. As these examples suggest, election manipulation networks are usually pyramidal, with actors at each level responsible for overseeing a larger number of actors at the next level down [@hale_patronal_2014]. Political candidates’ dependence on agents raises the possibility that agents’ may not always behave as the boss might prefer [@rundlett2016deliver] These are not easy problems for incumbents to solve, as actors at every step in the chain may have incentives to misrepresent their loyalty and effort on the boss's behalf [@harveyWhyAllowLocal2022].

While both principals and agents may participate in electoral manipulation, their underlying incentives diverge in important ways. Political principals benefit directly from manipulation [@greene_why_2007;@magaloni2006] since it improves their chances of winning close elections [@lehoucq2002] and widens their margin of victory [@gehlbach2015electoral;@simpser2013]. They gain utility, in other words, from each added vote. Agents, by contrast, are primarily motivated by credible access to patronage resources: the jobs, rents, and other benefits that come with participation in a political leader's network [@diaz2006federalism;@lust_okar2006;@reuter2012subnational]. A neighborhood broker, for instance, may seek a local administrative position through which rents can be extracted [@zarazaga2014brokers], while a schoolteacher serving as an election administrator in Russia may participate in ballot-stuffing only to preserve her own salary or benefits [@Forrat2018]. These divergent incentives can create a classic principal-agent problem. Because principals cannot perfectly monitor their agents' behavior, an agent may attempt to shirk her assigned manipulation tasks while still hoping to retain her place in the patronage network---pocketing the reward without bearing the risk.

In order to solve these problems, and ensure that a directive to manipulate the election issued at the top of the pyramid is in fact carried out across the bottom, incumbents need three things. First, incumbents must have access to benefits that can be shared with subordinates, to reward them for their efforts. Front-line agents do not directly benefit from each manufactured vote they generate. Instead, agents perform their assigned tasks in order to remain embedded within a principal’s patronage network. For example, Russia’s primary election-monitoring group recorded numerous incidents of voters being pressured to support the ruling party by their employers during the 2011 election. The following example is representative:

> At Kindergarten No. 620 [in St. Petersburg], a meeting was held in which employees were compelled to take absentee ballots in order to vote on school grounds. It was said that otherwise the district would be cut off from funding, but that voting by absentee would be rewarded with cash bonuses and time off. …It was pointed out that [Duma] Deputy S. Shatunovskii (a member of United Russia) had done a lot for the district and it was necessary to support him [@golos_analytical_2011].


As the anecdote illustrates, local school administrators pressured their employees with the risk of job loss and the promise of bonuses, in order to remain within the ruling party’s patronage network. This sort of voter pressure / vote-buying is common in sectors that rely on state patronage for their success [@frye2014]. Other forms of manipulation which rely more directly on state actors, such as ballot-stuffing or falsification of results, are also carried out in order to retain access to patronage. Principals in electoral authoritarian regimes tie access to the state and its associated opportunities for rents and patronage to electoral success [@diaz2006federalism;@lust_okar2006;@reuter2012subnational;@reuter2015], and can use the same resources to penalize opponents [@mcmann2006economic]. This creates a powerful incentive for local agents to boost the principal’s vote-share by whatever means are available, including misuse of the election administration apparatus, in order to remain within the privileged network. 


Second, because election manipulation of the type studied here is by definition illegal (even in the most authoritarian cases), incumbents need to be able to credibly promise their subordinates that they will not be punished for carrying out their assigned tasks. Exposure of an individual's illegal attempt to influence the election can carry criminal, civil, professional, reputational, and personal risks. The individual may face civil lawsuits or criminal prosecution, which---even in the most favorable circumstances---requires them to retain legal representation and devote time to the case. Loss in court can result in penalties like fines, prison time, or loss of official position. In some contexts, conviction of a crime can lead to professional penalties, including dismissal. Even probation, a relatively lenient penalty, brings restrictions on an individual's movements and activities and increased monitoring by the state. These are all possible negative consequences for participating in election manipulation, which weigh against the negative consequences of refusing to manipulate (i.e. punishment by the principal). Crucially, as I argue below, these risks exist even if the incumbent remains in power.

Even the most closed authoritarian regimes have competing incentives here. On the one hand, they may desire to protect their agents in order to promote manipulation in the future. On the other hand, they have incentives to allow a degree of judicial independence and transparency. More independent courts enhance regime legitimacy, reduce corruption, and increase investment [@Moustafa2008;@tsaiWhatMakesAnticorruption2022]. Furthermore, by allowing some agents to be exposed and punished, the incumbent may burnish the overall image of the election. 'Of course, a small number of our supporters were overzealous and bent the law,' this approach implies, 'but the legal system will handle these exceptional cases.' Naturally this is a bad place to be for the scapegoated agent.


Consequently, courts in non-democratic regimes do sometimes act to redress low-level electoral violations. For example, Popova [-@popova2012politicized] finds that district courts in Russia were more likely to hear election-related cases in competitive districts, and that pro-government candidates were not systematically more likely to win than pro-opposition candidates (pp. 94-95). More dramatically, beginning in the 1970s, the combination of legal reforms criminalizing certain electoral malpractices, the creation of more independent bodies to enforce those laws, and public and legal contestation by opposition parties largely cleaned up elections in authoritarian Mexico [@serraVoteBuyingIllegal2016;@eisenstadt_courting_2003]. Ultimately these changes helped usher out the ruling PRI after seven decades in power. 

Courts often hear charges against election officials for election tampering, but they can also adjudicate cases against ordinary individuals accused of other types of manipulation:  vote-buying, voter pressure, voter impersonation, and multiple voting [@Orozco-Henriquez2010]. Since authoritarian rulers have incentives to create a court system that does, on occasion, rule against the regime's supporters [@ginsburg_rule_2008;@popova2012politicized;@hendleyEverydayLawRussia2017;@Harvey2022], this can create acute risks for front-line agents in cases where exposure is more likely. In 1999, for example, Russian courts ruled against election commissioners accused of electoral malfeasance (including fraud allegations) in about half of cases [@Solomon2004]. A report on the punishment of election commissioners for violations of the election law from 2009 to 2015 in Russia found that, while most infractions are punished by small fines, significant punishments could be brought in cases with sufficient local political pressure [@golos__2015]. In some cases recorded by the monitoring group, election commissioners were found guilty of criminal offenses and faced stiff penalties, including fines of over half an average annual salary. Chapter 6, in this volume, shows further evidence of such risks in modern, more authoritarian Russia.

Such risks may have high or low probabilities of being realized, depending on individual context. Local agents are valuable to principals in part because of their deep knowledge of their local environment, which better enables them to monitor voters, distribute clientelistic benefits, or otherwise alter election results [@frye2014;@zarazaga2014brokers]. However, this local knowledge also allows agents to make strategic judgments about the level of local risk involved in manipulating an election in particular ways. They may abstain, or---in more competitive settings---may stop mobilizing voters or switch parties if the status quo becomes too risky [@stokes2013brokers, pp. 121-126]. 

The risk to agents has two components: the likelihood that a particular action will be exposed, and the likelihood that it will subsequently be punished. For example, the presence of election monitors makes it more likely that manipulation will be exposed [@kelley2012], and can deter manipulation [@hyde_catch_2011;@sjoberg_autocratic_2013] at particular polling sites. Similarly, when opposition parties have limited or no representation on election commissions, pro-incumbent manipulation is harder to expose and easier to accomplish [@kovalov_electoral_2014;@bader_osce_2012;@calingaert_election_2006]. <!--Monitors are more likely to be present in politically open territories [@Buzin2016], and more likely to be effective in more competitive districts [@asunka2017electoral].--> Local media can also play an important role in exposing criminal corruption [@usherHowLoudDoes2024], of which election manipulation can be an example. Once publicly exposed, individual agents' risks can still be mitigated if the likelihood of punishment is low. In cases where a dominant party machine exercises control over regional courts, opposition party figures are less likely to pursue complaints in regional courts [@popova2006], reducing the risk to agents of engaging in manipulation. 

Finally, the incumbent must be able to convince his subordinates that he will remain in power through the election and beyond; that is, that his ability to mete out rewards and punishments will be lasting [@hale_patronal_2014;@gehlbach2015electoral;@simpser2013]. If the principal appears less likely to control access to patronage due to electoral defeat or intraparty rivalry, her offer of post-election patronage will appear less viable to agents, reducing their incentive to work on her behalf [@hale_democracy_2006]. When one patronage network controls a large share of resources, agents have a strong incentive to support the principal: access to rents and resources outside that network is limited, competing offers of patronage by opposition figures are necessarily discounted, and punishment of defectors by exclusion from the network seems assured [@hale_patronal_2014]. In a society characterized by multiple patronage networks, by contrast, the credibility of an individual principal’s offer is contingent on the likelihood that the principal will win the election or leadership struggle. As a result, clients ‘hedge their bets or pin their hopes on different networks in an uncoordinated fashion’ [@hale_patronal_2014, p. 72]. Consequently, agents are more strongly incentivized to participate in electoral manipulation efforts when patronage networks are more consolidated. 

[NOTE: Add details here on how the same dynamic is at work when it comes to protection of front-line agents from consequences....]


Finally, manipulation on a national scale can be very expensive, and principals’ resources are not limitless. Even relatively cost-effective tactics like co-opting employers to pressure voters requires monitoring efforts and rewards for compliant businesses [@frye2014, p. 207]. Agents and brokers engaged in falsification or other types of manipulation must still be organized and compensated [@Langston2009mexico]. Vote-buying, however, is especially costly [@lehoucq2002;@wang2007], and such efforts become increasingly expensive as competitiveness increases [@corstange2018clientelism]. As a result, incumbents are likely to prefer centralized forms of manipulation in low risk areas, due to their cost-effectiveness. This pattern has been documented both domestically in Russia [@harvey_manipulation_2016] and cross-nationally [@vanham2015sticks]. Consequently, if higher local constraints make agents less willing to tamper with elections in administrative ways, principals may find agents both more expensive to hire (as they turn toward vote-buying and similar tactics) and more likely to shirk their duties on election day (as they become harder to monitor). This limits the ability of principals to compensate for higher competitiveness by boosting payments for agents. 

To summarize, low-level actors will be more willing to engage in electoral manipulation when the rewards are high and the risks are low. The rewards are well-understood; they typically involve participation in the incumbent's patronage network (providing access to jobs, career advancement, opportunities for enrichment, favors, and so on). The risks have been less well understood. Even in authoritarian regimes, incumbents have an incentive to permit the independent operation of the justice system to some degree. Even where he has firm control over the police and the courts, the incumbent may still have incentives to allow a small proportion of agents to be penalized for electoral crimes, in order to bolster the overall legitimacy of the election and the regime. While prospective agents cannot know *a priori* whether they will be protected, they can use their local knowledge to estimate the risk of exposure and subsequent punishment. Where the possibility of exposure and punishment is perceived to be high (relative to the patronage rewards), agents should be less willing to take risks to manipulate on the incumbent's behalf. However, as the next section describes, this dynamic does not mean that elections will necessarily be cleaner; instead, risk pushes agents into harder-to-detect forms of manipulation that are costlier to incumbents.

### Variation in manipulation tactic as response to agent risk

While ballot-stuffing, voter pressure, and falsification can all add to the incumbent's tally in the election, considerable scholarship has been invested in understanding why incumbents may prefer one strategy or another. Incumbents may prefer a certain mix of strategies in order to evade observation [@asunka2017electoral] and loss of legitimacy [@vanham2015sticks], due to resource constraints [@greene_why_2007] or availability [@Frye2018], to avoid appearing weak [@Harvey2020] or to evade the strictures of modern electoral procedure [@kuo_teorell_2017]. With few exceptions [@rundlett2016deliver;@Harvey2019], front-line agents' cooperation with incumbents' preferences is often assumed.

However, front-line agents do indeed have agency, and are not indifferent among the choices on the menu of manipulation. In particular, different illegal election manipulation tactics can be traced back to their individual perpetrators with varying degrees of difficulty. This affects the degree of personal risk to which the agent is exposed. Table \@ref(tab:attribution) summarizes these differences. To be clear, it is likely not typically the case that the principal is trying to get the agent to adopt one manipulation tactic, but the agent chooses another. Instead, as conditions change, it becomes harder for principals to recruit agents to perform certain kinds of tasks (e.g. precinct officials to stuff ballot boxes), forcing them to rely on different agents who perform different tasks (e.g. party operatives to buy votes).

```{=latex}
% Please add the following required packages to your document preamble:
% \usepackage{booktabs}
\begin{sidewaystable}
\centering
\begin{tabular}{@{}lllll@{}}
\toprule
\textbf{Manipulation tactic} & \textbf{Perpetrators known} & \textbf{Location known} & \textbf{Time known} & \textbf{Attributability} \\ \midrule
Falsification                & Yes (Officials)                & Yes      & Yes       & High     \\
Ballot-stuffing              & Possibly (Officials or voters) & Possibly & Partially & Moderate \\
Vote-buying / voter pressure & Rarely (Various)               & No       & No        & Low      \\ \bottomrule
\end{tabular}
\caption{Variation in how attributable election manipulation tactics are to perpetrators}
\label{tab:attribution}
\end{sidewaystable}
```

To my knowledge, there have been no prior studies of the factors that make electoral crimes more or less attributable to the perpetrator. However, there is a detailed literature in criminology that examines the 'solvability factors' that contribute to the likelihood of suspect arrest and case clearance in other crimes.^[While some research in this literature focuses on violent crime, the bulk of the literature focuses on solvability factors of non-violent 'volume crimes' like burglary.] An influential early study of policing in American cities concluded that "If information that uniquely identifies the perpetrator is not presented at the time the crime is reported, the perpetrator, by and large, will not be subsequently identified" [@greenwoodCriminalInvestigationProcess1975, p. ix]. This finding has been consistent in more recent research [@coupeModellingPoliceSuccess2001;@coupeDaylightDarknessTargeting2006;@olphinSolvingBurglaryOffences2021;@robinsonFactorsInfluencingPolice2009]. The effects can be large; one study finds that being caught at the scene increases the likelihood of attribution of a burgary or theft by as much as 20,000 percent (odds ratio 207.4); on the other hand, a simple description of the suspect increases the likelihood of attribution by only 40 percent [@robinsonFactorsInfluencingPolice2009].  A comprehensive study of UK policing found that the strongest predictor of solvability is having caught the perpetrator at the scene of the crime, though this is rare; cases where the crime is known to have taken place in a narrow time window are also more easily solved [@UnderstandingAttritionProcess]. On the basis of these trends, criminal cases are sometimes divided into three categories [@eckSolvingCrimesInvestigation1983]. First, there are cases with so few 'leads' that no amount of police effort is likely to result in a suspect being apprehended. Second, there are cases with enough initial evidence that an arrest could be made with sufficient devotion of police effort and resources. Finally, there are those cases "where the suspect has been positively identified, [which] will usually result in an arrest, even with only minimal investigative effort" [@brandl1994relationshp].  

Electoral crimes can be mapped onto these features identified in criminology research. Falsification of the vote count is the electoral crime most easily attributable to its perpetrators. Only the election officials, who are typically publicly named individuals, can count, tabulate, and record the election results; the individuals responsible for any discrepancies are thus easily identifiable. Moreover, counting the votes takes place at a known location (the polling place), as does tabulation (higher level election commissions); these activities also take place at known times (after the close of polling). Election monitors, unsurprisingly, take advantage of these facts to detect attempted manipulations.The OSCE Election Monitoring Handbook, for instance, notes that observers "should select one of their assigned polling stations at which to observe the closing procedures, and then remain there for the entire vote count"; it goes on to list detailed descriptions of the kinds of activities that monitors should be alert to [@officefordemocraticinstitutionsandhumanrightsElectionObservationHandbook2010, p. 79]. 

Similar instructions are provided for monitoring tabulation. An election monitoring guidebook from the National Democratic Institute (NDI) states that "Monitors should take note of who is present inside the voting station.... Election officials are responsible for administering the voting process.... [monitors] should observe and record the conduct of election officials in order to deter fraud, to help correct inadvertent mistakes, as well as detect and record actual irregularities" [@nationaldemocraticinstituteHowDomesticOrganizations1995, p. 71]. Due to their power, and the fixed time and location of their efforts, election officials are obvious targets of attention for those who seek to monitor and expose election fraud. This makes committing fraud an exercise in considerable risk for such officials, if they are operating in a context where monitoring by NGOs, parties, or citizens is vigorous.
    

At the other end of the spectrum of attribution are techniques where the relevant violation happens away from the polling place, both in space and in time. The actors involved are diverse and often non-public, including voters' employers and managers [@Frye2018;@fryeWorkplacePoliticsHow2025], local mayors and councilors [@Nunez2018;@Mares2019], civic organizations [@hollandMachineClientelistBrokers2015], labor unions [@LarreguyCesarMontielOleaPabloQuerubin2017], partisan neighborhood brokers [@Szwarcberg2015;@Berenschot2019], and others. Ample scholarly evidence attests to the difficulty that even their patrons have in monitoring brokers' behavior [@Aspinall2014;@stokesBrokersVotersClientelism2013;@langstonWhyClientelistBrokers2023]. Observers likewise face difficulties. The NDI handbook notes that observers should devote some attention to the atmosphere immediately outside the polling place, and should note "the identities (*or descriptions*)" of the people involved in incidents of bribery or intimidation [@nationaldemocraticinstituteHowDomesticOrganizations1995, p. 74, emphasis added]. The OSCE handbook has detailed instructions on how to evaluate the pre-election and election-day period, but unsurprisingly makes no mention of how to observe vote-buying or voter intimidation away for the polling place [@officefordemocraticinstitutionsandhumanrightsElectionObservationHandbook2010], beyond an evaluation of the formal rules limiting abuse of government resources [@officefordemocraticinstitutionsandhumanrightsHanbookObservationElection2021]. The Carter Center takes a similar approach in its guidelines for observers [@thecartercenterElectionObligationsStandards].

Recognizing these difficulties, the Russian domestic election monitoring organization Golos aimed to recruit ordinary citizens in the observation of dispersed forms of manipulation. Training materials from Golos state: 

> "Elections are not just the voting day itself, but the three months of campaigning beforehand. During this period, voters may face pressure from their superiors and illegal campaigning. Officials who are prohibited from doing so may participate in it. You may also witness the illegal use of administrative and budgetary resources in the interests of one of the candidates. All this is called 'administrative resources.' Only the voters themselves can effectively respond to this blatantly illegal behavior."

Golos goes on to provide placards that citizens can print and distribute in public places, or post on walls, to inform others of their legal rights [@HowDealAdministrative2025]. The placard encourages citizens to record photographic, audio, or video evidence of violations, and provides QR-codes that link to the authorities' online complaint portals, and to Golos' crowdsourced election violation website. These documents all illustrate the challenges facing organizations that wish to monitor and deter election violations that take place away from the polling station, and---in the Golos example---the lengths the organization must go in order to try to make such techniques attributable and risky for perpetrators. It is perhaps not surprising in this context that Golos has been the subject of increasingly harsh legal repression, and was finally forced to disband in the summer of 2025 [@alexeystrelnikovRussiasElectionWatchdog2025].

Ballot-stuffing falls somewhere in between these two extremes. Illegal ballots can be cast by election officials, of course, but can also be cast by legitimate voters or by third-parties. However, ballot-stuffing can only occur where the ballot box is, and can only occur sometime between when voting starts and ends. As a result, it is much simpler for monitors attempt to observe this kind of manipulation than it is for vote-buying and voter-pressure, which are far more dispersed and involve a more diverse range of agents. 

Consequently, if agents are indeed motivated by the desire to avoid personal attribution of electoral misdeeds, it is to be expected that agents will be less interested in techniques higher on the ladder the more likely they are to be exposed. That is, holding other factors equal, in local areas where political opposition and activist civil society are limited, we should expect to see more falsification by election officials. As the risk of exposure increases due to greater opposition and/or civil society activity, manipulation should move down the ladder in Table \@ref(tab:attribution). Election officials should shift from falsification to ballot-stuffing, and then increasingly drop out of the manipulation enterprise in favor of less easily identifiable individuals. As the risk of exposure increases further, even these third-party individuals should be less willing to manipulate in and around the polling place; instead, the incumbent will need to rely on a broader network of agents distributed throughout society. As this dispersion increases, a given 'unit' of manipulation becomes more expensive for the incumbent, as principal-agent problems mount and monitoring agents becomes more difficult.

This insight---that election-manipulating agents constrain their principals' options---produces a unique test of the regime-strength model of manipulation. Traditionally, explanations of variation in type of electoral manipulation has emphasized political leaders and their fear of legitimacy loss [@birch2011;@Schedler2013], their ability to monitor voters' compliance [@cox1981turnout;@stokes2005], their confidence in victory [@Hauser2018] or their access to certain resources [@vanham2015sticks]. Writing in 2013, Simpser noted that "the question of why some tactics of electoral manipulation are chosen over others in particular circumstances remains an open one," but sketched an expectation that incumbents would choose more cost-effective tactics over less cost-effective ones [-@simpser2013, pp. 28-29]. 

These theories suggest distinct predictions at the national and local levels. On the one hand, in a close election, theories that hinge on legitimacy costs suggest that incumbents should prioritize fraud in less-competitive regions. This is because fraud is the most cost-effective election-day manipulation strategy, but it requires control of the local election administration in order to implement. In more competitive regions, such models would seem to predict a decline in manipulation across all strategies. The difficulty in controlling the election administration in contested regions makes fraud difficult, while vote-buying, voter pressure, and voter intimidation are all more visible strategies; being directly visible to voters, their potential legitimacy cost is high if such efforts are widespread [@Schedler2013;@birch2011]. A principal-focused theory of manipulation that emphasizes legitimacy costs should thus predict that all types of election-day manipulation will decrease with the risk of exposure, and that fraud should predominate where the risk of exposure is low.

Different predictions emerge if, instead, the cost-effectiveness of a given strategy for incumbents is in large party conditioned by *agents'* incentive structures (rather than by legitimacy costs to principals). We should expect to see fraud decrease with local risk of exposure, as in the principal-focused approach. However, we should expect to see *less attributable*, though still visible forms of manipulation, *increase* with local risk of exposure. This outcome is expected because incumbents are not deterred from manipulating by legitimacy costs; indeed, they seek to demonstrate their power and impunity through the use of manipulation [@simpser2013]. However, as local risks of exposure increase, it becomes increasingly difficult to pressure election officials into engaging in attributable falsification. Instead, incumbents must rely on less attributable techniques like vote-buying and voter-pressure, despite their significantly greater cost and lower reliability.

<!-- [Think about using the terms principal-risk vs. agent-risk models of manipulation? Possibly in addition to 'regime strength model of manipulation and protest'] -->

Theories of manipulation that focus solely on principals' incentives should generally favor increased election fraud. As electoral outcomes become more uncertain, both the likelihood of losing office and the likelihood of significant post-election backlash increase. Incumbents are thus in a position of needing to significantly boost their vote-count while minimizing the visibility of manipulation. Falsification (and to a lesser extent ballot-stuffing) meets these criteria most effectively. It is very cost effective, requiring only that the incumbent have influence over members of the electoral administration and that they mis-report the results of the election. It does not require large networks of agents, is easily monitored (e.g. by setting vote-share and turnout targets), and can be kept hidden from voters.  

## Summary and general expectations of theory

The core of this theory is that front-line agents of election manipulation campaigns in authoritarian regimes and electoral democracies face real risks of exposure and punishment. When deciding whether and how to participate in an election-manipulation scheme, agents must weigh the risks of exposure against the risks of displeasing their political patrons.^[The risk of being cut off from the patronage network for failing to deliver sufficient votes is real. However, the risk is mitigated by the fact that principals can only imperfectly monitor their agents. It is difficult for a principal to know, for instance, how much of a positive electoral result is due to the agent's efforts and how much is due to her own local popularity. Moreover, it is difficult for the principal to know how many votes are being produced per unit of cost, and how much the agent is pocketing for himself. Incumbents have developed a variety of tools to try to circumvent this problem, like turnout-buying [@gans-morse_varieties_2014] and rewarding agents for public rallies [@szwarcberg_political_2014]. These methods are imperfect, and some---like maintaining original, correct election protocols in addition to the official, doctored versions---actually increase the risk of exposure to agents. Consequently, while the probability that electoral misdeeds will be exposed can sometimes be low, so too can the probability that defection will be discovered by the principal.] Knowing this, in order to survive against a strong opposition, incumbents must invest in the tools needed to solve principal-agent problems. They must centralize control over patronage resources in their domain, to better offer rewards to agents and entice them away from the opposition. This theory thus expects that when incumbents face stronger opposition threats will *invest more heavily in the tools social control*. They will be more likely to centralize control over patronage resources, to invest in repressive capacity, and to seek influence over the legal system.

Second, the theory predicts that incumbents who develop those capacities will use them to effectively and extensively manipulate elections. This follows the logic laid out by Simpser [-@simpser2013], who argues that incumbents have strong incentives to demonstrate their capacity to manipulate elections in order to influence other actors' behavior. In other words, the theory predicts that *incubments should manipulate more when they face strong oppositions*, rather than moderate their behavior, as conventional wisdom might hold. 

Incumbents are willing to take this risk, according to the theory, because they know that the capacity to manipulate elections overlaps with the capacity to suppress protest movements. The same tools that enable incumbents to solve principal-agent problems vis-a-vis front-line election agents also allow them to maintain loyalty within their networks and among the security services. As a result, theory predicts that, when post-election protests do occur, *greater electoral manipulation will be associated with quicker defeat of protest movements.*

Finally, the mechanism underlying the theory---agent-centered decision-making in the context of principal-agent problems---also yields testable hypotheses. The model assumes that agents face serious personal risks when they engage in illicit manipulation, even in highly authoritarian settings. This implies that *some agents must face serious criminal or other personal penalties when caught cheating in elections*. In the presence of such risks, the theory predicts that it will be more difficult to recruit agents to perform illicit acts that are easily attributable to the perpetrator. As a result, *when the local risk of exposure is high, falsification should be less common, while dispersed techniques like vote-buying should be more common*. Lastly, we should expect agents to update their estimation of local risks over time. *When an agent is harshly punished for illicit manipulation, subsequent manipulation in that region should decline.* However, by the same token, *when an exposed agent receives little to no penalty for illicit manipulation, subsequent manipulation in that region should increase.*

## Conclusion

By shifting the analytical focus from leaders' incentives to those of front-line agents, this theory identifies new constraints on election manipulation efforts: those factors which increase the likelihood that perpetrators of illicit manipulation will be identified and punished. As such factors---like local political competition, independent courts and prosecutors, and active local media and civil society organizations---become more prominent, it is more difficult for incumbents to recruit agents to perform the most attributable forms of manipulation. Unfortunately for incumbents, these are also the techniques that tend to be most cost-effective; it is far cheaper to add five hundred votes to the ruling party's tally at the stroke of a pen, than to actually *buy* five hundred votes from the community. This helps explain how authoritarian regimes can disintegrate from the bottom-up, as opposition groups steadily gain power at the local level; it also points toward policy mechanisms that can help uphold election integrity.

However, it also suggests that protest risk will rarely deter incumbents from engaging in as much electoral manipulation as they can, as they steadily develop greater and greater social control. This is a pessimistic account for democratization in authoritarian regimes, which also highlights some possible 'red lines' for democratic erosion in established democracies. Democratic incumbents who succeed in politicizing control over patronage resources and over the legal system are building tools that may in able them to win rigged elections *and* survive the associated popular blowback.

