# Conclusions


In August 2020, the Central Election Commission of Belarus declared that incumbent president Alexander Lukashenko had won the presidential contest with 81 percent of the vote; with turnout at 84 percent, this was purportedly a landslide endorsement of the five-term president amid the covid-19 pandemic. Almost immediately, mass protests sprang up across the country; the protest movement persisted for months against a harsh campaign of repression [@onuchBelarusCrisisPeople2022]. At one point, as much as fifteen percent of the population was in the streets in protest, on par with Ukraine's Orange Revolution [@gerasimovBelarusianPostcolonialRevolution2020] and far in excess of the 3.5 percent that stands a 'rule of thumb' for successful mobilization efforts [@chenowethCivilResistanceWhat2021]. The size and scale of the protest movement proved a significant challenge to the regime [@wayWhy2020Belarusian2023]. There was ample evidence in the pre-election period that a protest movement would emerge after a rigged election [@mateo2022]. In light of classic models of electoral manipulation, it is worth wondering why Lukashenko made such "mistaken decisions with regard to candidate registration [and] committing massive fraud..." [@stykowMakingSenseSurprise2023, p. 815] rather than manipulate less blatantly or even step down.

Of course, many answers to that question can be advanced with regard to a single case. Despite its unpopularity, the Lukashenko regime had many other sources of strength [@@leventogluSynthesizingTheoriesAuthoritarian2025].  The same mechanisms which the Lukashenko regime relied on to ensure lopsided electoral victory---a large and politicized state sector, a well-resourced security apparatus, and a pliant judiciary---could potentially be relied on to help the government outlast the protest movement [@wayWhy2020Belarusian2023;@deikaloRuleLawBelarus2025]. Lukashenko could also lean on economic and security assistance from Russia to bolster his position. Yet the loyalty of Belarusian elites was not guaranteed; as the protests grew in size and the regime's repressive tactics intensified, a wave of resignations occurred across the security forces [@SituationLawEnforcement]. Despite this, the bulk of the security forces remained loyal. One dissenting police officer explained his colleagues' loyalty, saying that the security forces believed Lukashenko would survive the protests and that they "simply fear him more than they fear retribution from outside" [@pehlmanShouldIStay2024, p. 13]. Could the extensive illicit manipulation of the election contributed to such perceptions of durability? The regime-strength model of manipulation would suggest so.  

Throughout this book, I have made three main claims. First, I have argued that illicit electoral manipulation entails personal risks for the low-level agents who perpetrate it. Chapter 3 provides qualitative and quantitative evidence of this, drawing on a novel dataset of Russian court decisions on alleged electoral violations. Descriptively, the court data shows that thousands of pro-regime agents have faced legal consequences for illicit manipulation from 2010 to 2021, a time frame that encompasses deepening authoritarianism in Russia. Even when spared any further penalty, such legal proceedings entail financial, reputational, and logistical costs for the accused; in Russia, some may even lose their jobs in the public sector as a result of criminal prosecution. Among those who are convicted, many face relatively light penalties---though even a suspended prison sentence carries substantial restrictions to one's liberty. Nevertheless, courts have imposed large fines on a substantial minorioty of election-rigging agents in Russia; these can amount to roughly six months' average wages. (For comparison, one might imagine a public schoolteacher in the United States being fined roughly one half of median income in the US: about $30,000.)

The second major claim I make is that these personal risks, which are inherent to illicit manipulation efforts, create principal-agent problems that meaningfully constrain incumbent's ability to manipulate elections. To overcome these problems, incumbents must offer election-manipulating agents a mix of patronage rewards and protection from possible punishment. When the risks of exposure and punishment appear high to potential agents, they will be less willing to participate in highly attributable forms of manipulation. In particular, it will become harder for incumbents to recruit election officials to falsify results. They may find more willing recruits to perform less attributable tasks, like vote-buying and voter pressure. But these tactics are less desirable for incumbents in some ways; they are far more costly, less cost-effective, and more public-facing. Consequently, as the risk of exposure for agents increases, we should observe less falsification and more dispersed forms of manipulation, conditional on the existence of consolidated patronage networks to fund such efforts. Ultimately, as patronage networks are dismantled and legal impunity for electoral crimes reduced, illicit electoral manipulation should give way to licit manipulation (e.g. gerrymandering, malapportionment) or free and fair elections.

Though that final prediction is outside the scope of this book, which focuses on authoritarian regimes, the other three implications are tested using election forensic analysis in Chapters 3, 4, and 5. Chapters 3 and 4 focus on the Russian case. Using precinct-level data from national elections from 2003 to 2021 (amounting to approximately one million observations), I estimate the severity of two categories of illicit manipulation. I estimate falsification using last-digits distribution [@beber2012] and deviance [@Skovoroda2017] tests, and the resampled kernel density method [@Rozenas2017]. Using my own adjustment of a turnout test [@myagkov_forensics_2009], to focus on 'non-standard' ballots (i.e. absentee and mobile ballot-box votes), I estimate vote-buying and voter pressure in the Russian context.

Linking the judicial outcomes data with the estimates of fraud, in Chapter 3, demonstrates the impact of agent risk on manipulation directly. Once caught up in the Russian legal process (itself a kind of machinery), it is difficult for individuals to emerge unscathed. Police, investigators, prosecutors, and judges all have incentives to successfully convict individuals caught committing an easily attributable crime like falsification. However, by the same token, they have incentives to avoid taking on more difficult cases of vote-buying and voter pressure. In regions where an agent is convicted of an electoral crime and given a harsh penalty, election-forensic analysis shows that falsification drops in the next election. By contrast, when convicted agents receive the proverbial slap on the wrist, evidence of fraud appears to increase in the next election. Finally, an analysis of the relationship between judicial punishments and election manipulation in Dagestan shows this relationship holds on a sub-regional level. Criminal punishment of illicit electoral malpractice throws a wrench in the machinery of manipulation by highlighting the risk to future agents. Permissive courts, however, help oil the machinery by showing agents they are more likely to be protected if exposed.

Chapters 4 and 5 test the proposition that increasing risk of attribution for electoral crimes should shift overall patterns of manipulation away from falsification and other forms of malpractice that take place in the polling place. Instead---as long as incumbents can afford it---overall manipulation should shift toward more dispersed tactics like vote-buying and voter pressure. Chapter 4 tests this prediction in the Russian case. Using multiple election forensic techniques, I estimate the degree of (highly attributable) falsification in each region, along with the degree of (less attributable) dispersed techniques like voter pressure and multiple voting. The results confirm that falsification declines as regional competitiveness increases. And, as predicted here but contrary to classical expectations, elections do not become cleaner in those regions; rather, the evidence shows that dispersed forms of manipulation increase as fraud declines. This pattern is to be expected in a case like Russia (from 2001 to 2021), where pockets of local contestation coexist with abundant patronage resources increasingly consolidated by the national executive.


Chapter 5, on Ukraine, shows how the shift to dispersed tactics plays out in the context of even greater local contestation (in some regions) and less consolidated patronage resources. Using similar electoral forensic techniques as in the previous chapter, I find little evidence of systematic falsification in post-Orange Ukraine. Other, dispersed forms of manipulation remain detectable, however, especially in favor of 'pro-Eastern' candidates and parties. This pattern is to be expected in the Ukrainian case (2004 - 2014), where the pro-Eastern coalition is effectively centered around the Party of Regions while the pro-Western coalition remains more divided and rivalrous. Risks to agents are, on average, lower for pro-Eastern agents operating in supportive regions than for pro-Western agents as a result. In addition, historical legacies of imperial and Soviet rule have left some of Ukraine's eastern regions with greater urbanization and industrial concentration, along with less independent and active civil society compared to the western Ukrainian average. As a result, the structural determinants of dispersed manipulation---for instance, the ability to pressure large groups of industrial workers into voting---are more developed in some eastern regions.

Chapter 5 also illustrates how dispersed forms of manipulation are sensitive to the availability of patronage resources. It is far more expensive to mobilize a thousand individuals to cast actual ballots for a party than it is to falsify a thousand votes with the stroke of an election officer's pen. Not only must the voters themselves be incentivized to vote (and perhaps monitored for compliance), a number of middlemen must also take their cut. All of these agents have incentives to shirk their responsibilities to their principal while pocketing the payment. As a result, it is costly and complicated to deliver widespread manipulation in this mode; large-scale dispersed manipulation efforts can only be effected when patronage resources are plentiful and under consolidated control. We see this pattern in the Ukrainian election-forensic data. Evidence of pro-Eastern dispersed manipulation increases when pro-Eastern Viktor Yanukovych is president and the constitution favors the presidency over the parliament. We also see more manipulation when regional oligarchs are aligned in their support for particular candidates and parties.  


The third major claim of this book concerns the macro-level implications of a theory of election manipulation that centers agent risk. Since front-line agents have incentives to avoid the risks associated with illicit electoral manipulation, they must be persuaded that the benefits of participation outweigh the risks of exposure and punishment. To convince thousands of agents to simultaneously carry out illicit electoral manipulation, incumbents must be rich in patronage resources and appear capable of protecting most agents from personal consequences of their lawbreaking. When incumbents can pull this off---producing widespread illicit manipulation on election day---they send signals of these capacities to other actors in the system. 

Such signals act to bind elites in at least three ways: they serve as costly signals of incumbent strength, they generate a commitment mechanism for insider elites via the election outcome, and---as a result---produce a coordination mechanism for elites during post-election protests. First, by overcoming front-line agents' reservations, incumbents demonstrate control over substantial resources and/or strict control over the police, prosecutors, and courts.^[Such control has direct costs, in the provision of patronage resources to those in the criminal-legal system. It also has indirect costs; by reducing the independence of the system, incumbents damage their own legitimacy and forego a variety of other benefits.] Large-scale illicit manipulation thus serves as a costly, believable signal of the incumbent's resource capacity and control over a large portion of the coercive apparatus. Since these same resources and capacities can be useful to the incumbent in defeating challengers, illicit electoral manipulation serves as a costly signal of the incumbent's strength.

Second, the manipulated election outcome creates a commitment mechanism for elites currently aligned with the incumbent. The rigged election serves is an offer of resource distribution within the incumbent winning coalition that would be difficult for the incumbent to reverse [@svolik_politics_2012]. By padding its vote-share through illicit manipulation, the incumbent party has shrunk the winning coalition relative to its size under a free-and-fair vote on election day. It has thus committed to a distribution of resources that will favor loyal elites at the expense of outsiders and the general public [@BuenodeMesquita2005]. If a rigged election sparks mass protest, elites presently aligned with the regime must decide whether to side with the protesters or the incumbent. Siding with the protesters is deeply risky for incumbent elites; a re-run of the election under conditions of mass mobilization and anger about manipulation is likely to make election rigging very difficult. A new election is almost certain to be cleaner and less favorable to the incumbent coalition than the (rigged) status quo. Since such an election might yield a much less favorable distribution of resources for today's insiders, such elites have a strong incentive to defend the rigged election against post-election protest waves. The outcome of the Orange Revolution, which not only changed the elites in the winning coalition but also ushered in significant institutional reforms, clearly illustrates this risk for insiders.

Third, the costly-signal and commitment-mechanism aspects of the rigged election help fix expectations about other elites' behavior. Imagine a regional governor considering whether to throw his resources against protesters in his region. Part of this calculation is based on his estimation of whether or not the incumbent will survive the protest wave, which is itself a function of whether or not other elites remain loyal. Aware of his own efforts (or lack thereof) to manipulate the election illicitly and the results in his region, the governor can gauge the efforts of his fellows as well [@rundlett2016deliver]. Perceiving that illicit electoral manipulation was widespread across the country, the governor will anticipate that other governors (along with diverse other elites) will make similar judgments. As a result, he can expect that other elites will back the incumbent, owing to the costly signal of resources and coercive capacity illicit manipulation generates, and the difficulty of negotiating a better deal with the opposition. As he expects larger numbers of other elites to support the incumbent, it becomes more appealing for our governor to do likewise. At the same time, other elites make the same calculation; the expectation that incumbent elites will remain loyal thus becomes a self-fulfilling prophesy [@hale_patronal_2014].

For these reasons, I argue that risk to agents is at the heart of a *regime-strength model of electoral manipulation*. Incumbents that can overcome agents' risk aversion to produce large-scale illicit manipulation send costly signals of strength that induce elite loyalty. As a result, I expect that more extensive illicit manipulation will be associated with quicker demise for post-election protest movements (rather than the opposite, as some previous theories would predict). 

Chapter 6 presents extensive, quantitative, cross-national evidence in favor of the regime-strength model. The results show that, among authoritarian regimes and electoral democracies, the governments that manipulate *more* defeat protest movements more quickly. Further analysis demonstrates that the relationship is not endogenous; incumbents are not manipulating more when they know they face a weak opposition. Using all 1,000+ observations in the dataset (i.e. all elections, not solely those that were followed by protest) multiple model specifications show that authoritarian governments manipulate *more extensively* when they face a greater risk of post-election protest. In addition, incumbent electoral defeat is not driven by protest risk, but rather by structural limitations on the incumbent's ability to produce electoral manipulation. In other words, incumbents are generally better served by manipulating elections more, rather than less, and they tend to behave accordingly. These results contradict a long-standing view in political science that greater reliance on election manipulation indicates deeper political weakness. In so doing, they indicate that a deterrent model---in which the risk of protest deters incumbents from manipulation---is misconceived.


Where does this leave scholars and proponents of liberal democracy? The regime-strength model of manipulation helps us better understand authoritarian behaviors in the electoral sphere. In recent years, for example, Russia has experimented with online voting---a system so transparently ripe for abuse that pluralities of citizens object to it in polls. The legitimacy cost of such a system is high, but it solves the principal-agent problem by eliminating agent risk. Electronic voting removes the publicly known, low-level election official from the act of falsification. It also removes the act from the polling place, both in time and in space. When election results can be generated by an algorithm, no one is at risk and shirking ceases to be a problem. Moves like this are more intelligible under the framework discussed in this book, than one in which manipulation is always cheap talk.

We should also be attentive to the implications of this theory for democratic backsliding. As incumbents in democratic societies seek to aggrandize power, this framework suggests we should be especially concerned about efforts to (re)build patronage networks and to increase legal impunity for agents. In the American context, at the time of writing, the incumbent president is seeking to politicize the civil service, to change the rules for voter registration and voter ID, to subordinate the courts, and to pardon (or secure state pardons) for individuals convicted of election schemes in 2020. These are not only a scattered array of undemocratic behaviors; rather they are a set of reforms that would increase the incentives for front-line agents to manipulate elections on the incumbent's behalf.

 

Instead, those of us who study electoral manipulation and authoritarian politics---and those of us who wish to see governments be more fully accountable to their citizens---should look more closely at the principal-agent logic of electoral manipulation to find ways to deter manipulation. What institutions, norms, or other conditions tie agents more closely to their principals? Under what conditions do those ties fray, as principal-agent problems worsen? Exposure of illicit manipulation and associated criminal-legal risk are the main factors at work in breaking those links in this study. If the courts, rather than the streets, are where the machinery of manipulation is most vulnerable, then the study of judicial independence and legal accountability deserves a more central place in the literature on authoritarian resilience---and in the practical work of democratic reform.


For instance, as with many aspects of authoritarian governance, independent courts pose a dilemma for ruling parties. On the one hand, perhaps authoritarian rulers might benefit from a judicial system that protected all regime agents from legal consequences of electoral crimes. Judges might, for example, be made aware that they will lose their posts if they convict a pro-regime agent. But doing so would require the judicial system to be highly open to politicized meddling. As a result, authoritarian rulers would lose the many benefits they obtain from partially independent courts: improved legitimacy, easier resolution of elite disputes, and protection of investments. Since authoritarian leaders benefit from a judicial system with a degree of real independence, they cannot credibly commit to protect each and every agent from criminal-legal risks. 

States and international organizations seeking to promote democracy might use authoritarian governments' interest in partially independent courts as a point of leverage. When non-democratic governments seek some foreign policy benefit in negotiations with pro-democracy interlocutors (e.g. more favorable access to the European Union market), negotiators might tie that benefit to reforms that improve *de facto* independence of the judicial and criminal-legal systems. In this way, organizations with some leverage [@levitsky2010] might make independent judicial systems more attractive to authoritarian governments, influencing how they resolve the dilemma. In turn, more independent courts and more effective police and prosecutors should increase the risk of illicit manipulation for agents, intensifying the principal-agent problem and driving a shift toward less cost-effective forms of manipulation. Over time, as competitiveness increases and risks to agents rise, such changes may ultimately lead to cleaner elections as they did in the American and British case studies provided in Chapter 2. 

From one perspective, this book could be read as a pessimistic account of citizens' role in promoting or defending democracy. If the threat of mass protest does not deter illicit manipulation, and if extensive manipulation actually helps unify incumbent elites, there might seem to be little room for ordinary citizens to defend their democratic rights. I offer two answers to this interpretation. First, nothing in this book should be read to suggest that protesting against a rigged election is wrongheaded, useless, or unwise. There are many reasons to protest authoritarianism: to express grievances, to demonstrate solidarity, to build momentum and organizational capacity, and to issue a challenge to those in power (among others). Doing so under the threat of harsh physical repression takes great courage and often great moral clarity. Protest movements really can contribute to political openings in authoritarian regimes, and they really can help plant the seeds for future democratic movements.

Second, even in the regime-strength model of electoral manipulation, individuals and organizations can still play a crucial role in improving election integrity. They do so not primarily by shaping incumbent risk via protest, but rather by shaping agents' risk of exposure and punishment. Opposition party activists, election monitors, independent journalists and ordinary voters can raise these risks. Like protesters, these actors are challenging the regime in a way that takes great courage and dedication. Unlike protesters, they often do so in obscurity. Pro-democracy organizations might consider how to better equip such actors with the tools and training to detect illicit electoral malpractice, report it to the authorities, and put pressure on the criminal-legal system to act. Scholars might likewise investigate what methods and conditions best enable election monitors, lawyers, and civil society groups to make illicit electoral manipulation costly for front-line agents, laying the groundwork for freer and fairer elections in the future.


<!--
Furthermore, the incumbent cannot perfectly monitor all of his agents. Agents are often selected for their local knowledge, and the secrecy of the ballot makes it difficult for incumbents to track how many manipulated votes a particular agent delivers. A risk-averse agent may be able to minimally tamper with the election (if at all), and hope that she is still rewarded by her patron. How are the agents political supervisors to know what proportion of the votes on the election return are manufactured by the agent? This problem cannot be easily solved even for the most direct forms of falsification; requiring agents to keep two sets of election returns (clean and doctored) further exposes them to legal risk if caught. -->




