# Appendix I: Measuring electoral manipulation

\chaptermark{Appendix I}



Personal electoral manipulation, like falsification or vote-buying, is often clandestine and almost always illegal; as a result, accurate measurement of electoral manipulation has posed a significant challenge for social scientists and practitioners. This challenge has, however, led to considerable methodological innovation. Scholars have developed several techniques for estimating the severity of electoral manipulation, each with advantages and disadvantages.

Historians and social scientists first began to address this problem through archival methods. Allegations of electoral manipulation could be found in the archives of those institutions charged with resolving such disputes: courts, legislatures, and other election management bodies. O'Gorman [-@ogormanVotersPatronsParties1989] examines allegations of manipulation in the House of Commons in Hanoverian England, while a pioneering study by Lehoucq and Molina [-@lehoucq2002] investigates more than 1,300 allegations of manipulation heard by the Costa Rican Congress and provincial electoral councils in the first half of the twentieth century. Similarly, Ziblatt [-@ziblatt2009] examines electoral disputes submitted to the German Reichstag between the onset of universal male suffrage in 1871 and 1912. Others have turned to reports of manipulation in newspaper archives [@cox1981turnout].

This approach has the considerable advantage of unearthing rich qualitative detail about the methods of manipulation allegedly applied, and the conditions under which they were used. For instance, Ziblatt draws on historical details from his dataset of electoral disputes, in combination with other historical records, to demonstrate how local state capture by elites led to greater alleged electoral manipulation in areas where local landowners were most powerful [@ziblatt2009, pp. 15-18]. Research into historical manipulation efforts has provided a wealth of details about the mechanisms by which party agents tampered with elections [@argersinger1985new;@reynoldsSymbioticRelationshipVote1993]. They can also provide colorful details; anticipating this book's argument about legal risks to election-manipulating agents, Reynolds reports one election official defending his conduct before a state senate panel by noting "I ain't no writing expert" [-@reynoldsSymbioticRelationshipVote1993, p. 245].^[Another colorful anecdote comes from Summers' study of patronage and corruption in 1800s America. He reports that the 1853 election in New Orleans reported record numbers of voters in Democratic precincts, despite a pre-election plague of yellow fever that took 20,000 lives. Summers writes, "Splendid was Divine providence, jeered the New Orleans *Bee*, to show such selectivity! Strangers should learn from this to register [as Democrats] the moment they entered New Orleans" [@summersPlunderingGenerationCorruption1987, p. 54]. 

However, it also has the possible disadvantage of considerable selection bias, particularly when used in statistical analysis. As Lehoucq and Molina [-@lehoucq2002] themselves note, there is a longstanding concern that the use of formal allegations of manipulation as a measure of electoral manipulation is likely to be biased by the strategic incentives and local organizational constraints of the complaining party. In a region where one party dominates, though it may manipulate the election extensively, the minority party may have little incentive to bring an allegation before what may be a compliant judge, electoral commission, or regional legislature. Moreover, the minority party may have little in the way of volunteers, activists, or employees in the regiona capable of monitoring the election and reporting on any irregularities. On the other hand, in hotly contested regions, the losing party has a strong incentive to report on any misdeeds by the winning party, perhaps even exaggerating them (and downplaying any excessive zeal on the part of its own activists). As one historian of American politics in the 1800s writes, "Indeed, to cry 'fraud' was the regular pastime of whichever party lost an election, and the historian must treat the clamor with caution" [@summersPlunderingGenerationCorruption1987].  

Election monitoring by professional organizations, domestic and international, provide another source of information about the quality of elections, as defined by international standards [@elklitRiseElectionMonitoring1997]. In the years following the Cold War, states increasingly permitted international monitors to observe their national elections---even when they did not intend to hold fully free and fair contests [@kelley2008]. This development, over time, created a large corpus of election observation mission reports from intergovernmental organizations (e.g. the OSCE) and non-governmental organizations (e.g. the Carter Center), which scholars could draw on the study election integrity cross-nationally [@kelley2012;@Hyde2014a;@hyde_pseudodemocrats_2011]. As with archival sources, election monitoring reports can provide useful qualitative details on the methods by which election integrity was undermined. At best, their analyses are disinterested and should not suffer from the competitiveness-induced selection biases in archival data. Yet election monitors may be far from disinterested---so-called 'zombie' monitors may be invited specifically to paper over electoral malpractice in their reports [@bushZombiesAheadExplaining2024]. Furthermore, even legitimate observation missions may downplay their allegations in order to maintain good relations with the host government [@JudithKelley2010;@mochtakBiasEyeBeholder2022].

Beyond such strategic calculations, election monitoring reports are limited in other ways. First, in most cases they are aggregated to the national level; it is typically not possible for analysts to use election monitors' reports to study heterogeneous electoral manipulation in different regions of a country. Second, international monitors are highly constrained in the degree of access they have to the host's electoral process. The size of a typical observation mission ranges from a few dozen to roughly one hundred long-term observers, plus a small number of professional staff [@ObservationMissionModels]. There is often an insurmountable disparity between the number of precincts that a mission can monitor and the total number in the country. For example, during the 2012 presidential election in Russia. the OSCE fielded an observation mission consisting of 15 professional experts, 40 long-term observers, and 160 short-term observers. These 215 observers were tasked with reporting on an election that was conducted across 95,000 precincts. Of course, Russia's size makes it an extreme example. Nevertheless, observation missions always face a significant gap between the number of personnel they can field and the scope of their task. As such, observation missions monitor a small fraction of possible precincts. In part to make up for this limitation, observers often travel from precinct to precinct during election day; they may observe the opening of the polling place in one location, the process of voting at another, and counting at a third. Political parties can exploit this variation by shifting manipulation tactics and location in order to avoid detection [@sjoberg_autocratic_2013;@leeffersDoesElectoralObservation2019;@asunka2017electoral]. Election monitors may thus mis-estimate the degree to which an election has been tainted, and the locations in which electoral integrity was most compromised.

(Read more of this one: [@leeffersDoesElectoralObservation2019] for competitiveness and effect of monitoring on manipulation

These limitations contributed to the development of a new set of techniques for estimating the severity of electoral manipulation in the absence of any monitors: election forensic analysis. Election forensic analysis encompasses a "diverse set of statistical tools...to analyze numerical electoral data and detect where patterns deviate from" the patterns a clean electoral process is assumed to generate [@hicken2015guide]. Election forensics have compelling advantages. They rely on 'objective' data; that is, they utilize the same results that election officials present as the election outcome. Forensic analysis can be conducted even for elections where no monitors were permitted. Selection bias is limited, if not avoided entirely, since data is drawn from all available precincts. It allows for subnational comparisons of election integrity across regions of a country. However, election forensic approaches also have drawbacks. It requires fine-grained election results, which many authoritarian countries do not publish. It can generate false positives, especially when analysis is not well grounded in forensic theory [@Eggers2021] or local case context [@deckert2013patterns]. And, of course, it provides little in the way of qualitative detail.

Methodologists have developed a variety of electoral forensic techniques. Some of the earliest efforts in this area emerged in Russia in the early 1990s, notably by Sobyanin and Sukhovolsky (Sobyanin & Sukhovolsky, 1993; Buzin, 2019). Methods that compare precinct-level turnout to party vote-share, or that analyze the 'flow of votes' across parties between elections were likewise developed in the post-communist context [@myagkov_forensics_2009]. These techniques focus on overall votes, and thus estimate manipulation overall; they do not distinguish between specific techniques. More recent methods in the same vein include the ‘fingerprints’ method (Klimek et al., 2012; Jimenez et al., 2017) and mixture models that classify polling stations based on the likely degree of manipulation (Kalinin, 2019).

Other types of forensic tools attempt to discriminate among the types of manipulation employed. A widely cited example, popularized by Beber and Scacco (2012), involves analyzing the distribution of the final digits in vote counts. In a fair election, these digits should appear uniformly: each digit (0 through 9) should occur with roughly equal frequency. Human beings tend to be poor random-number generators, and as such, distributions that deviate from the uniform may signal human tampering (Harvey, 2016; Skovoroda & Lankina, 2016; undlett & Svolik, 2016). This kind of analysis only detects a specific kind of fraud---human falsification of results---since other tactics may still result in randomly distributed ones-digits. On the other hand, Harvey (Harvey, 2016) has adapted the turnout-based measure [@myagkov_forensics_2009] to identify some types of manipulation that result in actual ballots being cast (e.g. ballot-stuffing, multiple-voting, and vote-buying).

These tools are only as reliable as the assumptions on which they are based. While they should not be used in isolation to assess the overall integrity of an election, they offer valuable insights when combined with qualitative data like observer reports. A further challenge facing these tools is the possibility that authoritarian regimes may adapt their electoral process to evade detection. To take a recent example, ruling parties may introduce technologies like electronic voting to limit forensic scrutiny (Rothrock, 2021). Some scholars suggest that governments might even intentionally insert statistical anomalies into falsified results—--either as a covert signal to superiors or a subtle provocation to analysts (Kalinin & Mebane, 2017). Election forensics remains a dynamic field, with ongoing innovation, including the incorporation of machine learning techniques (Cantú, 2019; Cantú & Saiegh, 2011; Zhang et al., 2019).

Finally, expert surveys are used to evaluate election integrity at the national level. Such surveys, the best of which draw on in-country experts, should in theory aggregate a variety of sources of information; national experts take into account their own local, contextual knowledge in addition to relevant research on election integrity in their case. The Varities of Democracy project takes this approach; it aims to have at least five scholars or professionals "with deep knowledge of a country and a particular institution," with preference for citizens / residents of the country [@coppedge2025vdem, p. 29]. Expert ratings thus have the advantage of possibly incorporating several sources of knowledge in each expert's overall assessment. They are limited, however, in that they typically only apply at the national level, and can be subject to experts' biases [@levickHindsightBiasExpert2020;@littleMeasuringDemocraticBacksliding2024].^[Though others have found more sanguine evidence for expert reliability [@bergeron-boutinExpertBiasDemocratic2024].]


This book draws on all of these sources of information about election integrity, but relies most heavily on election forensic analysis (Chapters 4, 5, and 6), expert ratings (Chapter 3), and election observation reports (used throughout). This allows for an analysis that draws on the strengths of each method, while also compensating for their limitations.