# Theory: (SUBTITLE HERE)

\chaptermark{Theory}

This chapter summarizes the theoretical contribution of the book. In brief, the primary argument is this: that extensive electoral manipulation requires incumbents to solve considerable principal-agent problems, and that taking this proposition seriously requires us to reframe how we understand the relationship between electoral manipulation and post-election protest. Individuals tasked with illegal election manipulation undertake personal risk to do so, even in authoritarian regimes. Therefore, in order to recruit election-manipulating agents on the front line, incumbents must have command over considerable patronage resources (to reward agents) and be able to credibly assure law-breaking individuals will not face punishment. 

Incumbents who successfully deploy extensive electoral manipulation, therefore have capacities that can be used directly to defeat protest movements that may arise after the election. Patronage resources can be used to demobilize opponents and mobilize clients, and to co-opt social groups, parties, or factions into siding with the regime. Politicized police, security forces, and courts can enable the repression of protesters via the judicial system. The legal impunity for regime agents that can flow from such control over the courts can also be used to intensify the cost of protest, for exam through extra-judicial detentions and violence.

These are direct 'benefits' to incumbents of the capacities needed for extensive election manipulation. *Utilizing* those capacities by rigging the election also sends signals to elites that enhance the regime's durability during protest. Authoritarian leaders face protest risks, but also the risk of elite defection and coups. Indeed, one of the things that makes protest risky for incumbents is the possibility that significant, visible popular discontent will prompt an attempted coup. By rigging the election, the incumbent demonstrates to elites that it has the capacity to solve multi-layered principal-agent problems---signaling its deep pockets, control over the judicial apparatus, and ability to mobilize agents whose incentives do not align with those of the boss. All this makes the incumbent look more durable, which helps keep elites loyal during the protest. The lack of elite support for the protesters---and the provision of support to the incumbent---helps reduce the duration and severity of the post-election protest movement. 

Bluntly put, if incumbents can successfully produce extensive electoral manipulation, they are simultaneously inoculating themselves against the cost of post-election protest. This perspective upends a common expectation in scholarly research and democracy promotion in practice. It is often held that, as electoral manipulation increases in severity, the risk to incumbents also rises in the form of protest risk. This chapter articulates why the opposite can be true: more manipulation can actually make incumbents safer. The remainder of the book then demonstrates empirical evidence in favor of this theory.

This theory models behavior by incumbents, front-line agents, and (potential) regime opponents. In the next three sections, each of these actors' incentives and behaviors are described. The fourth section ties all three together, providing a synthesis and expected outcomes.

## Part 0: Defining manipulation

Over time, scholars have advanced four approaches toward the definition of electoral manipulation. Two of these are rooted in local understandings of election integrity, and two appeal to broader standards [@birch2011]. The first, and simplest, definition of electoral manipulation focuses on whether particular actions are violations of local electoral law. This, of course, poses two difficulties: what is legal in one context may be illegal in another, and---even more problematic---laws themselves may be structured to advantage one party over others. A second approach focuses on local norms, rather than (or in addition to) local legal conditions. Electoral behaviors that may be considered unacceptable in some contexts, may be broadly acceptable in others. This possibility has been especially important in studies of vote-buying, where some scholars have emphasized the coerciveness of the practice (e.g. with monitoring and punishment for defection), while others have emphasized cultures of reciprocity and mutual support which can underpin the vote-buying relationship and lead recipients to view such 'gifts' as legitimate [@Lawson2014;@Nichter2018a;@greeneMoneyCantBuy2024]. 

These local approaches to election integrity have, however, largely given way to approaches that make claims at universality. The third school grounds its understanding of electoral manipulation in international law---in particular the Universal Declaration of Human Rights and the UN International Covenant for Civil and Political Rights [@Norris2013]---and the subsequent development of global norms for election management and election monitoring [@kelley2008;@hyde_catch_2011]. Lastly, a fourth approach is grounded in democratic theory; it begins by identifying the elements that are necessary for a democratic election to take place, and defines election manipulation as institutions and behaviors which obstruct those elements. 

Though this last school of thought is founded upon democratic theory espoused by Dahl [-@dahlPolyarchyParticipationOpposition1971], among others, it has perhaps been most clearly articulated in Andreas Schedler's [-@schedler2002] "menu of manipulation." In it, Schedler identifies seven requirements for a democratic election to succeed, ranging from the delegation of power to elected positions (i.e. elected officials must hold real power, rather than ceremonial or ineffective positions) to the irreversibility of electoral outcomes. Other essential features of a democratic election include freedom to form parties and compete in elections, voting eligibility for all full members of the community, free formation and expression of preferences, and fair aggregation of preferences under the principle of 'one person, one vote.'

Here, I follow this latter school of thought for a broad definition of electoral manipulation. To paraphrase Shchedler [-@Schedler2013, p. 83], electoral manipulation in general refers to any and all techniques that limit the choices of political authorities among a community of free and equal citizens. The focus of this book, however, is on a subset of violations of the 'chain of democratic choice;' those tactics which are procedurally illegitimate and *carried out by individuals*. I refer to this class of manipulative tactics as *illicit, individual manipulation.* Election manipulation techniques are procedurally illegitimate when they break the established rules for allocating power [@beethamLegitimationPower2013]. <!--  or more broadly when they depart from the principles of neutrality, fairness, and voice [@vandenbosWhenWeNeed1998;@tylerWhyPeopleObey2006]. [NOTE: More on this from prior work?] -->

Illicit, individual manipulation excludes most examples of formal electoral manipulation identified by Schedler [-@schedler2002], such as the creation of biased electoral rules or longstanding disenfranchisement of groups of citizens. So long as these tactics are procedurally legitimate---insofar as they are adopted according to the law---they do not expose their perpetrators to personal legal risk. Legislators who approve gerrymandered maps, for instance, may expose themselves to some political risks if the decision proves unpopular. But they are unlikely to be charged with a crime for doing so. 


On the other hand, a wide variety of procedurally illegitimate forms of electoral manipulation are enacted by individuals around election time. These include---at minimum---vote-buying, voter pressure, ballot-stuffing, multiple voting, and falsification. This framing includes economic electoral intimidation [@fryeWorkplacePoliticsHow2025] and non-state forms of electoral violence, but would likely exclude officially state-sanctioned electoral violence like police disruption of opposition gatherings [@birchElectoralViolenceCorruption2020]. 

Do illicit, individual forms of manipulation merit book-length investigation? It is a well-developed position in the literature that incumbents should prefer to rely on exactly the opposite kind of manipulation (i.e. formal techniques), which tend to be less visible and thus less damaging to incumbents' legitimacy, and can also be highly reliable [@birch2011;@Norris2013;@Szakonyi2021]. Nevertheless, there are several reasons for scholars to focus on illicit forms of manipulation. 

First, it is this kind of manipulation---falsification, ballot-stuffing, vote-buying, and the like---which forms the backstop to other, more predictable forms of institutional manipulation. Gerrymandered districts and biased electoral systems can backfire when incumbent popularity is low. Even when the genuine opposition has been excluded from the ballot, and there is thus no risk of incumbent defeat, incumbents still often turn to deliberate, personal forms of electoral manipulation; uncompetitive elections tend to depress turnout, which incumbents must compensate for in order to maintain an image of electoral strength.

Moreover, these techniques are theoretically important as the kind that is most likely to spark protest (due to procedural injustice and revealed information about incumbent), *and* as the most likely to be called out by observers. Because procedurally illegitimate forms of manipulation break the rules, they simultaneously increase protest risk (i.e. incur legitimacy costs) and produce individual risk for the perpetrator. The importance of this latter factor, however, has not previously been developed.

## Part 1: What do authoritarian principals want from elections?

Authoritarian leaders face two general threats to their position: mass revolt from below, and removal in an elite coup [@svolik_politics_2012]. These threats create a dilemma: allocating too much of society's resources to elites risks popular revolt, while devoting too much to the collective good can risk a coup by elites in search of a better deal. Incumbents utilize elections and electoral manipulation to help manage this dilemma. Holding elections allows incumbents to gather information about the population and the opposition [@Geddes1989;@Miller2015a;@magaloni2006], as well as on the popularity and effectiveness of subordinates [@blaydes2011]. Elections help incumbents recruit ambitious politicians into their party and manage intra-elite disputes over resource distribution [@lust_okar2006]. Finally, an election which delivers a large margin of victory for the incumbent can send a signal that induces cooperation from other political actors [@magaloni2006].

Of course, holding an election introduces the possibility of losing an election. The first generation of research on electoral manipulation tended to assume that the main function of manipulation was to avoid electoral defeat. The competitiveness of the election and stakes of losing power are the main drivers of manipulation in this tradition. Incumbents have more to gain from election rigging when they are likely to narrowly lose the election without it [@nybladeWhoCheatsWho2008;@lehoucq2002;@kamSecretBallotMarket2017;@Birch2007;@Fukumoto2011], and when the prospect of losing carries significant costs [@ziblatt2009;@baturoDemocracyDictatorshipTerm2014;@acemoglu2005economic;@Schedler2013;@horzElectoralManipulationPolarized2021].  

Subsequent research identified broader benefits of rigged elections for leaders. In Simpser's [-@simpser2013] influential formulation, election manipulation is about more than merely winning elections; when manipulation is excessive and/or blatant, it can communicate information about the regime's resources and capacities. These signals may convince other actors in society that the incumbent is likely to remain in office in the future [@simpser2013].  By setting expectations around regime durability, manipulation can lead other actors in society to cooperate with the incumbent [@gehlbach2015electoral]. Costlier types of election manipulation may send more convincing signals of strength, reducing the likelihood of protest [@Harvey2020].

So, from the incumbent's perspective, electoral manipulation helps achieve electoral victory and can convey information about the incumbent's strength to others. But it also comes with costs. First, there are unavoidable material and organizational costs, which can be considerable. Using detailed data on ruling party expenditures on vote-buying in Taiwan in 1993, Wang and Kurzman [-@wang2007] estimate that a vote-buying effort in a single county could cost more than four million USD (in 1993 dollars)---about twelve times the legal campaign expenditure limit.


## Part 2: What do front-line agents want?



## Part 3: Why do regime opponents protest?



## Part 4: A regime-strength model of electoral manipulation